version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/hammer-api"
    target-branch: "Hammer-V1"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/hammer-frontend"
    target-branch: "Hammer-V1"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/hammer-agent"
    target-branch: "Hammer-V1"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "Hammer-V1"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
