export const PAYMENT_AUDIT_EVENTS = {
  PAYMENT_POSTED: "SALE_ORDER_PAYMENT_POSTED",
  PAYMENT_DENIED: "SALE_ORDER_PAYMENT_DENIED",
  PAYMENT_INVENTORY_DEDUCTION_SUCCESS: "SALE_ORDER_PAYMENT_INVENTORY_DEDUCTION_SUCCESS",
  PAYMENT_INVENTORY_DEDUCTION_FAILED: "SALE_ORDER_PAYMENT_INVENTORY_DEDUCTION_FAILED",
  ORDER_STATUS_CHANGED: "SALE_ORDER_STATUS_CHANGED_BY_PAYMENT",
} as const;
