export const PAYMENT_AUDIT_EVENTS = {
  PAYMENT_POSTED: "SALE_ORDER_PAYMENT_POSTED",
  PAYMENT_DENIED: "SALE_ORDER_PAYMENT_DENIED",
  PAYMENT_INVENTORY_DEDUCTION_SUCCESS: "SALE_ORDER_PAYMENT_INVENTORY_DEDUCTION_SUCCESS",
  PAYMENT_INVENTORY_DEDUCTION_FAILED: "SALE_ORDER_PAYMENT_INVENTORY_DEDUCTION_FAILED",
} as const;
