export const APPROVAL_REQUEST_TYPES = {
  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",
  CASH_SESSION_DISCREPANCY: "CASH_SESSION_DISCREPANCY",
  OPERATION_OVERRIDE: "OPERATION_OVERRIDE",
  RETURN: "RETURN",
  PRICE_OVERRIDE: "PRICE_OVERRIDE",
  CREDIT_EXCEPTION: "CREDIT_EXCEPTION",
  TRANSFER_EXCEPTION: "TRANSFER_EXCEPTION",
} as const;

export const APPROVAL_DECISIONS = {
  APPROVE: "APPROVE",
  REJECT: "REJECT",
} as const;
