export const CASH_SESSION_AUDIT_EVENTS = {
  OPENED: "CASH_SESSION_OPENED",
  CLOSE_REQUESTED: "CASH_SESSION_CLOSE_REQUESTED",
  CLOSED: "CASH_SESSION_CLOSED",
  AUTO_CLOSED: "CASH_SESSION_AUTO_CLOSED",
  AUTO_CLOSE_REVIEWED: "CASH_SESSION_AUTO_CLOSE_REVIEWED",
  DISCREPANCY_DETECTED: "CASH_SESSION_DISCREPANCY_DETECTED",
  DENIED: "CASH_SESSION_DENIED",
} as const;
