export const CASH_SESSION_AUDIT_EVENTS = {
  OPENED: "CASH_SESSION_OPENED",
  CLOSE_REQUESTED: "CASH_SESSION_CLOSE_REQUESTED",
  CLOSED: "CASH_SESSION_CLOSED",
  DISCREPANCY_DETECTED: "CASH_SESSION_DISCREPANCY_DETECTED",
  DENIED: "CASH_SESSION_DENIED",
} as const;
