export const SALE_AUDIT_EVENTS = {
  ORDER_CREATED: "SALE_ORDER_CREATED",
  ORDER_CREATE_DENIED: "SALE_ORDER_CREATE_DENIED",
  ORDER_LINE_ADDED: "SALE_ORDER_LINE_ADDED",
  ORDER_LINE_UPDATED: "SALE_ORDER_LINE_UPDATED",
  ORDER_LINE_REMOVED: "SALE_ORDER_LINE_REMOVED",
  ORDER_LINE_MUTATION_DENIED: "SALE_ORDER_LINE_MUTATION_DENIED",
  ORDER_SUBMITTED_PENDING_PAYMENT: "SALE_ORDER_SUBMITTED_PENDING_PAYMENT",
  ORDER_STATUS_CHANGED: "SALE_ORDER_STATUS_CHANGED",
  ORDER_SUBMIT_DENIED: "SALE_ORDER_SUBMIT_DENIED",
  // Anulación de facturas/órdenes desde el Centro de Comando (rol master).
  ORDER_CANCELLED: "SALE_ORDER_CANCELLED",
  ORDER_CANCEL_DENIED: "SALE_ORDER_CANCEL_DENIED",
} as const;
