export const SALE_AUDIT_EVENTS = {
  ORDER_CREATED: "SALE_ORDER_CREATED",
  ORDER_CREATE_DENIED: "SALE_ORDER_CREATE_DENIED",
  ORDER_LINE_ADDED: "SALE_ORDER_LINE_ADDED",
  ORDER_LINE_UPDATED: "SALE_ORDER_LINE_UPDATED",
  ORDER_LINE_REMOVED: "SALE_ORDER_LINE_REMOVED",
  ORDER_LINE_MUTATION_DENIED: "SALE_ORDER_LINE_MUTATION_DENIED",
  ORDER_SUBMITTED_PENDING_PAYMENT: "SALE_ORDER_SUBMITTED_PENDING_PAYMENT",
  ORDER_STATUS_CHANGED: "SALE_ORDER_STATUS_CHANGED",
  ORDER_SUBMIT_DENIED: "SALE_ORDER_SUBMIT_DENIED",
  ORDER_MANUAL_DISCOUNT_SET: "SALE_ORDER_MANUAL_DISCOUNT_SET",
  ORDER_MARKED_TEST: "SALE_ORDER_MARKED_TEST",
  ORDER_UNMARKED_TEST: "SALE_ORDER_UNMARKED_TEST",
  ORDER_VOIDED: "SALE_ORDER_VOIDED",
  // Snapshot completo del contenido de la venta (productos, cantidades, cliente,
  // totales) que se conserva como historial al marcar prueba o anular.
  ORDER_SNAPSHOT_ARCHIVED: "SALE_ORDER_SNAPSHOT_ARCHIVED",
  // Reversión de inventario aplicada al excluir una venta (RETURN_IN).
  ORDER_INVENTORY_REVERTED: "SALE_ORDER_INVENTORY_REVERTED",
} as const;
