import type { RoleCode } from "@prisma/client";

export const PERMISSIONS = {
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",
  APP_MASTER_ACCESS: "app.master.access",
  APP_BRANCH_ACCESS: "app.branch.access",
  APPROVAL_REQUEST_CREATE: "approval.request.create",
  APPROVAL_REQUEST_REVIEW: "approval.request.review"
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const basePermissions: Record<RoleCode, PermissionKey[]> = {
  SYSTEM_ADMIN: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_MASTER_ACCESS,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
  ],
  OWNER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_MASTER_ACCESS,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
  ],
  MASTER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_MASTER_ACCESS,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
  ],
  BRANCH_ADMIN: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
  ],
  SALES: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
  ],
  CASHIER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
  ],
  WAREHOUSE: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
  ],
};

export function getPermissionsForRole(role: RoleCode): PermissionKey[] {
  return basePermissions[role] ?? [];
}
