import type { RoleCode } from "@prisma/client";

export const PERMISSIONS = {
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",
  APP_MASTER_ACCESS: "app.master.access",
  APP_BRANCH_ACCESS: "app.branch.access",
  APPROVAL_REQUEST_CREATE: "approval.request.create",
  APPROVAL_REQUEST_REVIEW: "approval.request.review",

  // ── Production Module ──
  PRODUCTION_RECIPES_VIEW: "production.recipes.view",
  PRODUCTION_RECIPES_CREATE: "production.recipes.create",
  PRODUCTION_RECIPES_EDIT: "production.recipes.edit",
  PRODUCTION_BATCHES_VIEW: "production.batches.view",
  PRODUCTION_BATCHES_CREATE: "production.batches.create",
  PRODUCTION_BATCHES_COMPLETE: "production.batches.complete",
  PRODUCTION_COST_VIEW: "production.cost.view",
  PRODUCTION_DASHBOARD_VIEW: "production.dashboard.view",

  // ── Documentos e Impresión (FASE 3) ──
  DOCUMENT_PRINT: "document.print",
  DOCUMENT_REPRINT: "document.reprint",
  DOCUMENT_SKIP_PRINT: "document.skip.print",
  DOCUMENT_TEMPLATE_MANAGE: "document.template.manage",
  MANUAL_INVOICE_REGISTER: "manual.invoice.register",
  MANUAL_INVOICE_CANCEL: "manual.invoice.cancel",
  PRINT_SETTINGS_MANAGE: "print.settings.manage",
  PRINT_LOG_VIEW: "print.log.view",
  SALES_HISTORY_VIEW: "sales.history.view",
  MASTER_HISTORY_VIEW: "master.history.view",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** All production permissions for convenience */
const ALL_PRODUCTION_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.PRODUCTION_RECIPES_VIEW,
  PERMISSIONS.PRODUCTION_RECIPES_CREATE,
  PERMISSIONS.PRODUCTION_RECIPES_EDIT,
  PERMISSIONS.PRODUCTION_BATCHES_VIEW,
  PERMISSIONS.PRODUCTION_BATCHES_CREATE,
  PERMISSIONS.PRODUCTION_BATCHES_COMPLETE,
  PERMISSIONS.PRODUCTION_COST_VIEW,
  PERMISSIONS.PRODUCTION_DASHBOARD_VIEW,
];

/** All document/print permissions for convenience */
const ALL_DOCUMENT_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.DOCUMENT_PRINT,
  PERMISSIONS.DOCUMENT_REPRINT,
  PERMISSIONS.DOCUMENT_SKIP_PRINT,
  PERMISSIONS.DOCUMENT_TEMPLATE_MANAGE,
  PERMISSIONS.MANUAL_INVOICE_REGISTER,
  PERMISSIONS.MANUAL_INVOICE_CANCEL,
  PERMISSIONS.PRINT_SETTINGS_MANAGE,
  PERMISSIONS.PRINT_LOG_VIEW,
  PERMISSIONS.SALES_HISTORY_VIEW,
  PERMISSIONS.MASTER_HISTORY_VIEW,
];

const basePermissions: Record<RoleCode, PermissionKey[]> = {
  SYSTEM_ADMIN: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_MASTER_ACCESS,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
    ...ALL_DOCUMENT_PERMISSIONS,
  ],
  OWNER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_MASTER_ACCESS,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
    ...ALL_DOCUMENT_PERMISSIONS,
  ],
  MASTER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_MASTER_ACCESS,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
    ...ALL_PRODUCTION_PERMISSIONS,
    ...ALL_DOCUMENT_PERMISSIONS,
  ],
  BRANCH_ADMIN: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    PERMISSIONS.APPROVAL_REQUEST_REVIEW,
    // Documentos (FASE 3)
    PERMISSIONS.DOCUMENT_PRINT,
    PERMISSIONS.DOCUMENT_REPRINT,
    PERMISSIONS.DOCUMENT_SKIP_PRINT,
    PERMISSIONS.MANUAL_INVOICE_REGISTER,
    PERMISSIONS.MANUAL_INVOICE_CANCEL,
    PERMISSIONS.PRINT_LOG_VIEW,
    PERMISSIONS.SALES_HISTORY_VIEW,
  ],
  SALES: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    // Documentos (FASE 3)
    PERMISSIONS.DOCUMENT_PRINT,
    PERMISSIONS.DOCUMENT_SKIP_PRINT,
    PERMISSIONS.SALES_HISTORY_VIEW,
  ],
  CASHIER: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    // Documentos (FASE 3)
    PERMISSIONS.DOCUMENT_PRINT,
    PERMISSIONS.DOCUMENT_REPRINT,
    PERMISSIONS.MANUAL_INVOICE_REGISTER,
    PERMISSIONS.PRINT_LOG_VIEW,
  ],
  WAREHOUSE: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.APP_BRANCH_ACCESS,
    PERMISSIONS.APPROVAL_REQUEST_CREATE,
    // Documentos (FASE 3)
    PERMISSIONS.DOCUMENT_PRINT,
  ],
};

export function getPermissionsForRole(role: RoleCode): PermissionKey[] {
  return basePermissions[role] ?? [];
}
