import type { RoleCode } from "@prisma/client";
import type { SessionPayload } from "@/types/auth";

export const CAPABILITIES = {
  MASTER_DASHBOARD_VIEW: "master.dashboard.view",
  MASTER_USERS_VIEW: "master.users.view",
  MASTER_SESSIONS_VIEW: "master.sessions.view",
  MASTER_CASH_MONITOR_VIEW: "master.cash_monitor.view",
  SYSTEM_ADMIN_ACCESS: "system.admin.access",
  SYSTEM_ADMIN_ROLE_CONFIG: "system.admin.role.config",
  SYSTEM_ADMIN_SETTINGS: "system.admin.settings",
  MASTER_ACCESS: "master.access",
  MASTER_USERS_MANAGE: "master.users.manage",
  MASTER_CATALOG_MANAGE: "master.catalog.manage",
  MASTER_INVENTORY_VIEW: "master.inventory.view",
  MASTER_SALES_VIEW: "master.sales.view",
  BRANCH_DASHBOARD_VIEW: "branch.dashboard.view",
  POS_VIEW: "pos.view",
  POS_SELL: "pos.sell",
  POS_PRINT: "pos.print",
  POS_CREATE_DRAFT: "pos.create_draft",
  POS_EDIT_DRAFT: "pos.edit_draft",
  POS_CANCEL_OWN_DRAFT: "pos.cancel_own_draft",
  POS_SEND_TO_CASHIER: "pos.send_to_cashier",
  POS_DIRECT_COLLECT: "pos.direct_collect",
  POS_PRINT_QUOTE: "pos.print_quote",
  POS_PRINT_DELIVERY_ORDER: "pos.print_delivery_order",
  CASH_VIEW: "cash.view",
  CASH_OPEN: "cash.open",
  CASH_CHARGE: "cash.charge",
  CASH_CLOSE: "cash.close",
  CASH_SESSION_MANAGE: "cash.session.manage",
  CASH_BOX_VIEW: "cash_box.view",
  CASH_BOX_MANAGE: "cash_box.manage",
  CASH_SESSION_OPEN: "cash_session.open",
  CASH_SESSION_ASSIGN_OPERATOR: "cash_session.assign_operator",
  CASH_SESSION_USE: "cash_session.use",
  CASH_SESSION_CLOSE_REQUEST: "cash_session.close_request",
  CASH_SESSION_RECONCILE: "cash_session.reconcile",
  CASH_SESSION_CLOSE_FINAL: "cash_session.close_final",
  PAYMENT_QUEUE_VIEW: "payment.queue.view",
  PAYMENT_COLLECT: "payment.collect",
  PAYMENT_COLLECT_DIRECT: "payment.collect.direct",
  PAYMENT_VOID: "payment.void",
  PAYMENT_REFUND: "payment.refund",
  PAYMENT_PRINT_RECEIPT: "payment.print_receipt",
  CASH_MOVEMENT_CREATE: "cash_movement.create",
  CASH_MOVEMENT_APPROVE: "cash_movement.approve",
  CASH_MOVEMENT_VIEW: "cash_movement.view",
  OPERATING_EXPENSE_VIEW: "operating_expense.view",
  OPERATING_EXPENSE_CREATE: "operating_expense.create",
  // ── Finanzas & Contabilidad ──
  FINANCE_VIEW: "finance.view",
  FINANCE_MANAGE_EXPENSES: "finance.manage_expenses",
  FINANCE_VIEW_PAYROLL: "finance.view_payroll",
  FINANCE_MANAGE_PAYROLL: "finance.manage_payroll",
  FINANCE_VIEW_PRICING: "finance.view_pricing",
  FINANCE_MANAGE_PRICING: "finance.manage_pricing",
  FINANCE_REPORTS_EXPORT: "finance.reports_export",
  WAREHOUSE_VIEW: "warehouse.view",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_OPENING_BALANCE: "inventory.opening_balance",
  INVENTORY_IMPORT: "inventory.import",
  PRICING_VIEW: "pricing.view",
  PRICING_EDIT_BRANCH: "pricing.edit_branch",
  PRICING_EDIT_GLOBAL: "pricing.edit_global",
  PURCHASES_VIEW: "purchases.view",
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_APPROVE: "purchases.approve",
  PURCHASES_RECEIVE: "purchases.receive",
  TRANSFERS_VIEW: "transfers.view",
  TRANSFERS_CREATE: "transfers.create",
  TRANSFERS_APPROVE: "transfers.approve",
  TRANSFERS_DISPATCH: "transfers.dispatch",
  TRANSFERS_RECEIVE: "transfers.receive",
  PRODUCTION_VIEW: "production.view",
  PRODUCTION_RECIPES_MANAGE: "production.recipes.manage",
  BRAIN_VIEW: "brain.view",
  BRAIN_ACTIONS_MANAGE: "brain.actions.manage",
  BRANCH_CATALOG_VIEW: "branch.catalog.view",
  BRANCH_INVENTORY_VIEW: "branch.inventory.view",
  INVENTORY_MOVEMENT_POST: "inventory.movement.post",
  SALES_VIEW: "sales.view",
  SALE_RETURN_REQUEST: "sale.return.request",
  SALE_RETURN_APPROVE: "sale.return.approve",
  SALE_RETURN_EXECUTE: "sale.return.execute",
  SALE_CANCELLATION_REQUEST: "sale.cancellation.request",
  SALE_CANCELLATION_APPROVE: "sale.cancellation.approve",
  SALE_CANCELLATION_EXECUTE: "sale.cancellation.execute",
  CREDIT_NOTE_CREATE: "credit-note.create",
  CREDIT_NOTE_APPROVE: "credit-note.approve",
  DAMAGED_INVENTORY_VIEW: "damaged-inventory.view",
  DAMAGED_INVENTORY_ADJUST: "damaged-inventory.adjust",
  SALES_DRAFT_MANAGE: "sales.draft.manage",
  SALES_SUBMIT_PAYMENT: "sales.submit.payment",
  CASH_PAYMENTS_VIEW: "cash.payments.view",
  CASH_PAYMENTS_COLLECT: "cash.payments.collect",
  CASH_SESSION_OPERATE: "cash.session.operate",
  CASH_REVIEW: "cash.review",
  CASH_AUTO_CLOSE_REVIEW: "cash.auto_close.review",
  OPERATIONS_VIEW: "operations.view",
  OPERATIONS_MANAGE: "operations.manage",
  OPERATIONAL_DAY_OPEN: "operations.day.open",
  OPERATIONAL_DAY_CLOSE: "operations.day.close",
  OPERATIONAL_DAY_APPROVE_DELEGATE: "operational_day.approve.delegate",
  DISPATCH_VIEW: "dispatch.view",
  DISPATCH_MARK: "dispatch.mark",
  APPROVAL_REQUEST_CREATE: "approval.request.create",
  APPROVAL_REQUEST_REVIEW: "approval.request.review",
  AUDIT_VIEW: "audit.view",
  REPORTS_EXPORT: "reports.export",

  // ── Production ──
  PRODUCTION_RECIPES_VIEW: "production.recipes.view",
  PRODUCTION_RECIPES_CREATE: "production.recipes.create",
  PRODUCTION_RECIPES_EDIT: "production.recipes.edit",
  PRODUCTION_BATCHES_VIEW: "production.batches.view",
  PRODUCTION_BATCHES_CREATE: "production.batches.create",
  PRODUCTION_BATCHES_COMPLETE: "production.batches.complete",
  PRODUCTION_COST_VIEW: "production.cost.view",
  PRODUCTION_DASHBOARD_VIEW: "production.dashboard.view",

  // ── Documentos e Impresión (FASE 3) ──
  DOCUMENT_PRINT: "document.print",
  DOCUMENT_REPRINT: "document.reprint",
  DOCUMENT_SKIP_PRINT: "document.skip.print",
  DOCUMENT_TEMPLATE_MANAGE: "document.template.manage",
  MANUAL_INVOICE_REGISTER: "manual.invoice.register",
  MANUAL_INVOICE_CANCEL: "manual.invoice.cancel",
  PRINT_SETTINGS_MANAGE: "print.settings.manage",
  PRINT_LOG_VIEW: "print.log.view",
  SALES_HISTORY_VIEW: "sales.history.view",
  MASTER_HISTORY_VIEW: "master.history.view",
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

const ALL_CAPABILITIES = Object.values(CAPABILITIES);

const ROLE_CAPABILITIES: Record<RoleCode, Capability[]> = {
  SYSTEM_ADMIN: ALL_CAPABILITIES.filter(c => !c.startsWith("production.")),
  OWNER: ALL_CAPABILITIES.filter(c => c !== CAPABILITIES.SYSTEM_ADMIN_ACCESS && c !== CAPABILITIES.SYSTEM_ADMIN_ROLE_CONFIG && c !== CAPABILITIES.SYSTEM_ADMIN_SETTINGS && !c.startsWith("production.")),
  MASTER: ALL_CAPABILITIES.filter(c => c !== CAPABILITIES.SYSTEM_ADMIN_ACCESS && c !== CAPABILITIES.SYSTEM_ADMIN_ROLE_CONFIG && c !== CAPABILITIES.SYSTEM_ADMIN_SETTINGS),
  BRANCH_ADMIN: [
    CAPABILITIES.POS_VIEW,
    CAPABILITIES.POS_SELL,
    CAPABILITIES.POS_PRINT,
    CAPABILITIES.POS_CREATE_DRAFT,
    CAPABILITIES.POS_EDIT_DRAFT,
    CAPABILITIES.POS_CANCEL_OWN_DRAFT,
    CAPABILITIES.POS_SEND_TO_CASHIER,
    CAPABILITIES.POS_DIRECT_COLLECT,
    CAPABILITIES.POS_PRINT_QUOTE,
    CAPABILITIES.POS_PRINT_DELIVERY_ORDER,
    CAPABILITIES.CASH_VIEW,
    CAPABILITIES.CASH_OPEN,
    CAPABILITIES.CASH_CHARGE,
    CAPABILITIES.CASH_CLOSE,
    CAPABILITIES.CASH_SESSION_MANAGE,
    CAPABILITIES.CASH_BOX_VIEW,
    CAPABILITIES.CASH_BOX_MANAGE,
    CAPABILITIES.CASH_SESSION_OPEN,
    CAPABILITIES.CASH_SESSION_ASSIGN_OPERATOR,
    CAPABILITIES.CASH_SESSION_USE,
    CAPABILITIES.CASH_SESSION_CLOSE_REQUEST,
    CAPABILITIES.CASH_SESSION_RECONCILE,
    CAPABILITIES.CASH_SESSION_CLOSE_FINAL,
    CAPABILITIES.PAYMENT_QUEUE_VIEW,
    CAPABILITIES.PAYMENT_COLLECT,
    CAPABILITIES.PAYMENT_COLLECT_DIRECT,
    CAPABILITIES.PAYMENT_VOID,
    CAPABILITIES.PAYMENT_REFUND,
    CAPABILITIES.PAYMENT_PRINT_RECEIPT,
    CAPABILITIES.CASH_MOVEMENT_CREATE,
    CAPABILITIES.CASH_MOVEMENT_APPROVE,
    CAPABILITIES.CASH_MOVEMENT_VIEW,
    CAPABILITIES.OPERATING_EXPENSE_VIEW,
    CAPABILITIES.OPERATING_EXPENSE_CREATE,
    // Finanzas de su sucursal (sin planilla: los salarios no se exponen a admin de sucursal).
    CAPABILITIES.FINANCE_VIEW,
    CAPABILITIES.FINANCE_VIEW_PRICING,
    CAPABILITIES.FINANCE_MANAGE_EXPENSES,
    CAPABILITIES.WAREHOUSE_VIEW,
    CAPABILITIES.DISPATCH_MARK,
    CAPABILITIES.INVENTORY_VIEW,
    CAPABILITIES.INVENTORY_ADJUST,
    CAPABILITIES.SALES_DRAFT_MANAGE,
    CAPABILITIES.SALES_SUBMIT_PAYMENT,
    // ── View capabilities ──
    CAPABILITIES.BRANCH_DASHBOARD_VIEW,
    CAPABILITIES.BRANCH_CATALOG_VIEW,
    CAPABILITIES.BRANCH_INVENTORY_VIEW,
    CAPABILITIES.SALES_VIEW,
    CAPABILITIES.SALE_RETURN_REQUEST,
    CAPABILITIES.SALE_RETURN_APPROVE,
    CAPABILITIES.SALE_RETURN_EXECUTE,
    CAPABILITIES.SALE_CANCELLATION_REQUEST,
    CAPABILITIES.SALE_CANCELLATION_APPROVE,
    CAPABILITIES.SALE_CANCELLATION_EXECUTE,
    CAPABILITIES.CREDIT_NOTE_CREATE,
    CAPABILITIES.CREDIT_NOTE_APPROVE,
    CAPABILITIES.DAMAGED_INVENTORY_VIEW,
    CAPABILITIES.DAMAGED_INVENTORY_ADJUST,
    CAPABILITIES.CASH_PAYMENTS_VIEW,
    CAPABILITIES.CASH_PAYMENTS_COLLECT,
    CAPABILITIES.CASH_SESSION_OPERATE,
    CAPABILITIES.CASH_REVIEW,
    CAPABILITIES.CASH_AUTO_CLOSE_REVIEW,
    CAPABILITIES.OPERATIONS_VIEW,
    CAPABILITIES.OPERATIONS_MANAGE,
    CAPABILITIES.OPERATIONAL_DAY_OPEN,
    CAPABILITIES.OPERATIONAL_DAY_CLOSE,
    CAPABILITIES.OPERATIONAL_DAY_APPROVE_DELEGATE,
    CAPABILITIES.DISPATCH_VIEW,
    // ── Production (view only for branch admin) ──
    // ── Governance & reporting ──
    CAPABILITIES.APPROVAL_REQUEST_CREATE,
    CAPABILITIES.APPROVAL_REQUEST_REVIEW,
    CAPABILITIES.AUDIT_VIEW,
    CAPABILITIES.REPORTS_EXPORT,
    // ── Documentos e Impresión (FASE 3) ──
    CAPABILITIES.DOCUMENT_PRINT,
    CAPABILITIES.DOCUMENT_REPRINT,
    CAPABILITIES.DOCUMENT_SKIP_PRINT,
    CAPABILITIES.MANUAL_INVOICE_REGISTER,
    CAPABILITIES.MANUAL_INVOICE_CANCEL,
    CAPABILITIES.PRINT_LOG_VIEW,
    CAPABILITIES.SALES_HISTORY_VIEW,
  ],
  SALES: [
    CAPABILITIES.POS_VIEW,
    CAPABILITIES.POS_SELL,
    CAPABILITIES.POS_PRINT,
    CAPABILITIES.POS_CREATE_DRAFT,
    CAPABILITIES.POS_EDIT_DRAFT,
    CAPABILITIES.POS_CANCEL_OWN_DRAFT,
    CAPABILITIES.POS_SEND_TO_CASHIER,
    CAPABILITIES.POS_PRINT_QUOTE,
    CAPABILITIES.BRANCH_DASHBOARD_VIEW,
    CAPABILITIES.BRANCH_CATALOG_VIEW,
    CAPABILITIES.SALES_VIEW,
    CAPABILITIES.SALES_DRAFT_MANAGE,
    CAPABILITIES.SALES_SUBMIT_PAYMENT,
    CAPABILITIES.APPROVAL_REQUEST_CREATE,
    // ── Documentos e Impresión (FASE 3) ──
    CAPABILITIES.DOCUMENT_PRINT,
    CAPABILITIES.DOCUMENT_SKIP_PRINT,
    CAPABILITIES.SALES_HISTORY_VIEW,
  ],
  CASHIER: [
    CAPABILITIES.CASH_VIEW,
    CAPABILITIES.CASH_OPEN,
    CAPABILITIES.CASH_CHARGE,
    CAPABILITIES.CASH_CLOSE,
    CAPABILITIES.CASH_SESSION_MANAGE,
    CAPABILITIES.CASH_BOX_VIEW,
    CAPABILITIES.CASH_SESSION_USE,
    CAPABILITIES.CASH_SESSION_CLOSE_REQUEST,
    CAPABILITIES.PAYMENT_QUEUE_VIEW,
    CAPABILITIES.PAYMENT_COLLECT,
    CAPABILITIES.PAYMENT_COLLECT_DIRECT,
    CAPABILITIES.PAYMENT_PRINT_RECEIPT,
    CAPABILITIES.CASH_MOVEMENT_VIEW,
    CAPABILITIES.CASH_MOVEMENT_CREATE,
    CAPABILITIES.BRANCH_DASHBOARD_VIEW,
    CAPABILITIES.CASH_PAYMENTS_VIEW,
    CAPABILITIES.CASH_PAYMENTS_COLLECT,
    CAPABILITIES.SALE_RETURN_REQUEST,
    CAPABILITIES.SALE_RETURN_EXECUTE,
    CAPABILITIES.SALE_CANCELLATION_REQUEST,
    CAPABILITIES.SALE_CANCELLATION_EXECUTE,
    CAPABILITIES.CREDIT_NOTE_CREATE,
    CAPABILITIES.CASH_SESSION_OPERATE,
    CAPABILITIES.OPERATIONS_VIEW,
    CAPABILITIES.APPROVAL_REQUEST_CREATE,
    // ── Documentos e Impresión (FASE 3) ──
    CAPABILITIES.DOCUMENT_PRINT,
    CAPABILITIES.DOCUMENT_REPRINT,
    CAPABILITIES.MANUAL_INVOICE_REGISTER,
    CAPABILITIES.PRINT_LOG_VIEW,
  ],
  WAREHOUSE: [
    CAPABILITIES.WAREHOUSE_VIEW,
    CAPABILITIES.DISPATCH_MARK,
    CAPABILITIES.INVENTORY_VIEW,
    CAPABILITIES.INVENTORY_ADJUST,
    CAPABILITIES.BRANCH_DASHBOARD_VIEW,
    CAPABILITIES.BRANCH_INVENTORY_VIEW,
    CAPABILITIES.INVENTORY_MOVEMENT_POST,
    CAPABILITIES.DAMAGED_INVENTORY_VIEW,
    CAPABILITIES.DAMAGED_INVENTORY_ADJUST,
    CAPABILITIES.DISPATCH_VIEW,
    CAPABILITIES.DISPATCH_MARK,
    CAPABILITIES.OPERATIONS_VIEW,
    // ── Production (warehouse can view and create batches) ──
    CAPABILITIES.APPROVAL_REQUEST_CREATE,
    // ── Documentos (FASE 3) ──
    CAPABILITIES.DOCUMENT_PRINT,
  ],
};

export function can(roleCode: RoleCode, capability: Capability): boolean {
  return ROLE_CAPABILITIES[roleCode]?.includes(capability) ?? false;
}

export function getCapabilitiesForRole(roleCode: RoleCode): Capability[] {
  return ROLE_CAPABILITIES[roleCode] ?? [];
}

/** Minimal session shape required for capability checks */
type CapabilitySession = Pick<SessionPayload, "globalRoles" | "branchMemberships"> | null;

export function canInBranch(session: CapabilitySession, branchId: string, capability: Capability): boolean {
  if (!session || !branchId) return false;
  if (session.globalRoles.includes("SYSTEM_ADMIN")) return can("SYSTEM_ADMIN", capability);
  if (session.globalRoles.includes("OWNER")) return can("OWNER", capability);
  if (session.globalRoles.includes("MASTER")) return can("MASTER", capability);

  return session.branchMemberships
    .filter((membership) => membership.branchId === branchId)
    .some((membership) => can(membership.roleCode, capability));
}

export function canInAnyAssignedBranch(session: CapabilitySession, capability: Capability): boolean {
  if (!session) return false;
  if (session.globalRoles.includes("SYSTEM_ADMIN")) return can("SYSTEM_ADMIN", capability);
  if (session.globalRoles.includes("OWNER")) return can("OWNER", capability);
  if (session.globalRoles.includes("MASTER")) return can("MASTER", capability);

  return session.branchMemberships.some((membership) => can(membership.roleCode, capability));
}
